export const SERVICES = [
  {
    id: "vasteras-route",
    name: "Västerås ↔ Arlanda / Stockholm",
    displayName: "Västerås ↔ Arlanda / Stockholm",
    description: "1000 SEK fixed — regional corridor",
    longDesc: "Västerås ↔ Arlanda / Stockholm fixed route package",
    price: 1000,
    priceLabel: "1000 SEK",
    icon: "map-pin",
    popular: true,
    duration: "Flexible",
    route: "Regional",
    tagline: "Featured fixed route.",
    features: ["1000 SEK fixed", "Västerås · Arlanda · Stockholm"],
    ctaLabel: "BOOK ROUTE",
  },
  {
    id: "airport-pickup",
    name: "Airport Pickup",
    displayName: "Arlanda to City",
    description: "Arlanda → City Center",
    longDesc: "Arlanda Airport → Stockholm City Center",
    price: 650,
    priceLabel: "650 SEK",
    icon: "plane-arrival",
    popular: true,
    duration: "45-60 min",
    route: "Direct route",
    tagline: "Fixed price. No surge. All inclusive.",
    features: ["Fixed price", "Flight tracking", "On-time guarantee"],
    ctaLabel: "BOOK AIRPORT PICKUP",
  },
  {
    id: "airport-dropoff",
    /** U+2011 non-breaking hyphen avoids “DROP-” / “OFF” line splits in narrow cards */
    name: "Airport Drop\u2011off",
    displayName: "City to Arlanda",
    description: "City Center → Arlanda",
    longDesc: "Stockholm City Center → Arlanda Airport",
    price: 595,
    priceLabel: "595 SEK",
    icon: "plane-departure",
    popular: false,
    duration: "45-60 min",
    route: "Door to door",
    tagline: "Fixed price. Flight tracking. On-time guarantee.",
    features: ["Fixed price", "Flight tracking", "On-time guarantee"],
    ctaLabel: "BOOK AIRPORT TRANSFER",
  },
  {
    id: "city-tour",
    name: "City Tour",
    displayName: "City Tour",
    description: "4 hours city exploration",
    longDesc: "4 hours Stockholm exploration",
    price: 2500,
    priceLabel: "2500 SEK",
    icon: "landmark",
    popular: false,
    duration: "4 Hours",
    route: "6+ Stops",
    extraLabel: "Guide",
    tagline: "Professional guide. Photo stops included.",
    features: ["4 hours duration", "6+ locations", "Professional guide", "Photo stops"],
    highlights: [
      "Gamla Stan Walking",
      "Vasa Museum",
      "Photo Stops",
      "Royal Palace",
      "Modern Districts",
      "Professional Guide",
    ],
    ctaLabel: "BOOK CITY TOUR",
  },
  {
    id: "custom-route",
    name: "Custom Route",
    displayName: "Custom Route",
    description: "Any Stockholm destination",
    longDesc: "Get instant quote for any Stockholm destination",
    price: null,
    priceLabel: "Quote",
    icon: "map-pin",
    popular: false,
    duration: "Flexible",
    route: "Custom stops",
    tagline: "Flexible routes tailored to your needs.",
    features: ["Flexible", "Any distance", "Custom stops"],
    hasForm: true,
    ctaLabel: "GET QUOTE & BOOK",
  },
] as const;

export type ServiceId = (typeof SERVICES)[number]["id"];
